### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by francisrod01** [dashed/react-offline#15]
There's no way to prevent the `window` error in server-side.
I'm using `Next.js`, so the server-side is automatic.

I received this error on the browser and the system console:

```bash
ReferenceError: window is not defined
    at new Offline (/app/next/node_modules/react-offline/lib/index.js:39:25)
```

* I'm using `react@16.8.6`
* `react-offline@0.1.0`
* `react-dom@16.8.6`
* `next@8.1.0`

**Comment by dashed** [comment]
@francisrod01 Thanks for the heads up 👍 . 

I created a PR to refresh this library to address this issue at https://github.com/dashed/react-offline/pull/16 . 

I'll try to do some testing on a sample next.js project.
